default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV["DATABASE_PORT"] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restaurant_reservation_system_development


test:
  <<: *default
  database: restaurant_reservation_system_test

production:
  <<: *default
  database: restaurant_reservation_system_production
  username: restaurant_reservation_system
  password: <%= ENV["RESTAURANT_RESERVATION_SYSTEM_DATABASE_PASSWORD"] %>
